site_name: Project Documentation
site_description: Documentation for this engineering project
site_author: Alison Emilien

theme:
  name: mkdocs

nav:
  - Home: index.md
  - Setup: setup.md
  - Workflow: workflow.md
